language: go
go:
  - 1.14
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - goveralls -service=travis-pro
  - make test_travis
  - make build_travis

