apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-Beacon
spec:
  selector:
    matchLabels:
      name: kube-beacon
  template:
    metadata:
      labels:
        app: kube-beacon
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: beacon.jfrog.io/docker-local/kube-beacon:latest
        command: ["kube-beacon"]
        volumeMounts:
        - name: var-lib
          mountPath: /var
          readOnly: true
        - name: etc-lib
          mountPath: /etc
          readOnly: true
        - name: usr-bin
          mountPath: /usr/bin
          readOnly: true
        - name: cni
          mountPath: /*/cni/*
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: var-lib
        hostPath:
          path: "/var"
      - name: etc-lib
        hostPath:
          path: "/etc"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
      - name: cni
        hostPath:
          path: "/*/cni/*"