apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-Beacon
spec:
  template:
    metadata:
      labels:
        app: kube-beacon
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:latest
        command: ["kube-beacon"]
        volumeMounts:
        - name: var-lib
          mountPath: /var
          readOnly: true
        - name: etc-lib
          mountPath: /etc
          readOnly: true
        - name: usr-bin
          mountPath: /usr/local/mount-from-host/bin
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: var-lib
        hostPath:
          path: "/var"
      - name: etc-lib
        hostPath:
          path: "/etc"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"